d2w:
    log_filename: log.txt
    log_max_bytes: 1048576
    log_backup_count: 5

database:
    drupal_host: localhost
    drupal_username: minnpost
    drupal_password: minnpost
    drupal_database: minnpost.092515
    wordpress_host: localhost
    wordpress_username: minnpost
    wordpress_password: minnpost
    wordpress_database: minnpost.wordpress2
    # A user with CREATE privilege to create the tables
    admin_username: jonathanstegall
    admin_password: Gx8bZwG9UrEkpFWs

project:
    # The directory where you'll store the project files for this migration.
    default_project_path: ""    

############################################################
# Your migration SQL scripts
############################################################
sql:
    # This will normally be the database dump of a fresh WordPress installation.
    # It is not expected to change across different migration projects.
    wordpress_setup_script: "minnpost.wordpress.template.sql"

    # This will be the database dump of the client's Drupal installation.
    # Each migration project will have a specific dump file.
    drupal_setup_script: ""

    # An SQL script containing any custom setup queries.
    setup_sql_filename: ""
    
    # An SQL script containing any custom preparation queries.
    prepare_sql_filename: "custom.sql"

    # The standard migration SQL script may not work on all Drupal configurations.
    migrate_sql_filename: "migrate.sql"

    # An SQL script containing any custom deployment queries.
    deploy_sql_filename: ""
